//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface NSProgressValues : NSObject <NSSecureCoding>
{
    NSMutableDictionary *_userInfo;
    long long _totalUnitCount;
    long long _completedUnitCount;
    long long _childCompletedUnitCount;
    double _fractionCompleted;
    double _selfFractionCompleted;
    double _childFractionCompleted;
    NSString *_localizedDescription;
    NSString *_localizedAdditionalDescription;
    _Bool _isCancellable;
    _Bool _isPausable;
    _Bool _isCancelled;
    _Bool _isPaused;
    NSString *_kind;
    _Bool _isPrioritizable;
    _Bool _isFinished;
}

+ (id)decodableClasses;
+ (_Bool)supportsSecureCoding;
- (void)setIndeterminate:(_Bool)arg1;
- (_Bool)isIndeterminate;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

