//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GEOClientETATrafficUpdateRequest, GEOLocation, GEORoute, GEORouteAttributes, GEOWaypoint, NSData, NSTimer, VKAttributedRouteMatch;

@interface MKETAUpdater : NSObject
{
    id <MKETAUpdaterDelegate> _delegate;
    GEOClientETATrafficUpdateRequest *_currentETARequest;
    GEOLocation *_userLocation;
    VKAttributedRouteMatch *_routeMatch;
    GEORoute *_route;
    GEOWaypoint *_destination;
    GEORouteAttributes *_routeAttributes;
    long long _etaState;
    _Bool _allowRequests;
    _Bool _shouldUseConditionalRequest;
    double _requestInterval;
    NSTimer *_etaIdleTimer;
    double _lastETARequestTime;
    NSData *_directionsResponseID;
}

@property(retain, nonatomic) NSData *directionsResponseID; // @synthesize directionsResponseID=_directionsResponseID;
@property(nonatomic) double requestInterval; // @synthesize requestInterval=_requestInterval;
@property(nonatomic) _Bool shouldUseConditionalRequest; // @synthesize shouldUseConditionalRequest=_shouldUseConditionalRequest;
@property(nonatomic) _Bool allowRequests; // @synthesize allowRequests=_allowRequests;
@property(retain, nonatomic) GEOWaypoint *destination; // @synthesize destination=_destination;
@property(retain, nonatomic) GEORouteAttributes *routeAttributes; // @synthesize routeAttributes=_routeAttributes;
@property(retain, nonatomic) GEORoute *route; // @synthesize route=_route;
@property(retain, nonatomic) VKAttributedRouteMatch *routeMatch; // @synthesize routeMatch=_routeMatch;
@property(retain, nonatomic) GEOLocation *userLocation; // @synthesize userLocation=_userLocation;
@property(readonly, nonatomic) GEOClientETATrafficUpdateRequest *currentRequest; // @synthesize currentRequest=_currentETARequest;
@property(nonatomic) __weak id <MKETAUpdaterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)updateRouteWithETATrafficUpdateResponse:(id)arg1;
- (void)_addCurrentRouteToETARequest:(id)arg1 currentStepIndex:(unsigned long long)arg2 percentOfCurrentStepRemaining:(double)arg3;
- (_Bool)_shouldStartConditionalETARequest;
- (void)_continueUpdateRequests;
- (_Bool)_sendETARequest:(id)arg1 isUpdate:(_Bool)arg2;
- (void)_startConditionalConnectionETARequest;
- (void)_startStateWaitingForBestTimeStart:(id)arg1;
- (void)stopUpdateRequests;
- (void)startUpdateRequests;
- (void)_clearCurrentETARequest;
- (void)_clearTimer;
- (void)setEtaState:(long long)arg1;
- (void)reset;
- (void)dealloc;
- (id)initWithRoute:(id)arg1 destination:(id)arg2 routeAttributes:(id)arg3;
- (id)init;

@end

