//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MapKit/MKSearchCompletion.h>

@class GEOPlaceResult, GEOSearchRequest, GEOSearchResponse, MKMapItem;

__attribute__((visibility("hidden")))
@interface MKPlaceResultSearchCompletion : MKSearchCompletion
{
    GEOPlaceResult *_result;
    GEOSearchRequest *_request;
    GEOSearchResponse *_response;
    MKMapItem *_mapItem;
}

- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (void)applyToPlaceSearchRequest:(id)arg1;
- (void)sendFeedback;
- (id)mapItem;
- (_Bool)getCoordinate:(CDStruct_c3b9c2ee *)arg1;
- (id)highlightsForLine:(unsigned long long)arg1;
- (id)displayLines;
- (id)initWithPlaceResult:(id)arg1 response:(id)arg2 request:(id)arg3;

@end

