//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MapKit/MKSearchCompletion.h>

@class GEOSearchRequest, GEOSearchResponse, GEOSuggestionEntry;

__attribute__((visibility("hidden")))
@interface MKSuggestionEntrySearchCompletion : MKSearchCompletion
{
    GEOSuggestionEntry *_entry;
    GEOSearchRequest *_request;
    GEOSearchResponse *_response;
    unsigned long long _entryListIndex;
    unsigned long long _entryIndex;
}

- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (void)applyToPlaceSearchRequest:(id)arg1;
- (void)applyToLocalSearchRequest:(id)arg1;
- (void)sendFeedback;
- (id)calloutTitle;
- (id)queryLine;
- (_Bool)getCoordinate:(CDStruct_c3b9c2ee *)arg1;
- (id)highlightsForLine:(unsigned long long)arg1;
- (id)displayLines;
- (id)initWithSuggestionEntry:(id)arg1 response:(id)arg2 request:(id)arg3 entryListIndex:(unsigned long long)arg4 entryIndex:(unsigned long long)arg5;

@end

