//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AddressBookUI/ABStyleProvider.h>

@class CNContactStyle;

@interface ABContactStyleStyleProvider : ABStyleProvider
{
    CNContactStyle *_contactStyle;
}

@property(retain, nonatomic) CNContactStyle *contactStyle; // @synthesize contactStyle=_contactStyle;
- (id)memberHeaderBackgroundView;
- (id)groupHeaderBackgroudColor;
- (long long)headerViewBorderStyle;
- (id)memberSearchFieldBackgroundColor;
- (id)groupCellBackgroundColor;
- (id)membersSearchBackgroundColor;
- (_Bool)peoplePickerBarStyleIsTranslucent;
- (long long)peoplePickerBarStyle;
- (_Bool)shouldUsePeoplePickerBarStyle;
- (id)membersHeaderBackgroundColor;
- (id)membersHeaderContentViewBackgroundColor;
- (id)membersBackgroundColor;
- (id)groupCellTextColor;
- (id)groupsTableBackgroundColor;
- (id)memberNameTextColor;
- (id)cardValueTextColor;
- (id)cardLabelSelectedBackgroundColor;
- (id)separatorColorForCellStyle:(int)arg1;
- (id)cardCellDividerColorVertical:(_Bool)arg1;
- (id)cardSectionBackgroundColor;
- (id)cardCellBackgroundColor;
- (void)dealloc;
- (id)initWithContactStyle:(id)arg1;

@end

