//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ABPropertyGroupItem, ABPropertyIDSRequest, NSArray, NSMutableArray;

@interface ABPropertyBestIDSValueQuery : NSObject
{
    NSMutableArray *_validIDSItems;
    id <ABPropertyBestIDSValueQueryDelegate> _delegate;
    NSArray *_propertyItems;
    ABPropertyIDSRequest *_idsRequest;
}

@property(retain, nonatomic) ABPropertyIDSRequest *idsRequest; // @synthesize idsRequest=_idsRequest;
@property(retain, nonatomic) NSArray *propertyItems; // @synthesize propertyItems=_propertyItems;
@property(nonatomic) id <ABPropertyBestIDSValueQueryDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) NSMutableArray *validIDSItems; // @synthesize validIDSItems=_validIDSItems;
@property(readonly) ABPropertyGroupItem *bestIDSProperty;
- (void)cancel;
- (void)dealloc;
- (id)initWithPropertyItems:(id)arg1 service:(id)arg2;

@end

