//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AddressBookUI/CNContact.h>

@class NSArray, NSDateComponents, NSString;

@interface CNMutableContact : CNContact
{
}

+ (id)contactWithRecord:(void *)arg1 unify:(_Bool)arg2;
+ (id)contactWithRecord:(void *)arg1;
+ (id)contact;
- (struct __CFString *)_ABLabelFromCNLabel:(id)arg1;
- (void)_setStringMultiValueForProperty:(int)arg1 values:(id)arg2;
- (void)_setMultiValueForProperty:(int)arg1 values:(id)arg2 valueFromCNValue:(CDUnknownBlockType)arg3;
- (void)addProperties:(id)arg1 excludingProperties:(id)arg2 fromContact:(id)arg3;
- (_Bool)addToGroup:(void *)arg1;
- (_Bool)hasChanges;
- (_Bool)unlinkContact;
- (_Bool)linkToContact:(id)arg1;
- (_Bool)deleteContact;
- (_Bool)saveContactInAddressBook:(void *)arg1;
- (_Bool)saveContact;
@property(copy) NSArray *textTone; // @dynamic textTone;
@property(copy) NSArray *ringtone; // @dynamic ringtone;
@property(copy) NSArray *postalAddresses; // @dynamic postalAddresses;
@property(copy) NSArray *socialProfiles; // @dynamic socialProfiles;
@property(copy) NSArray *relatedNames; // @dynamic relatedNames;
@property(copy) NSArray *instantMessageAddresses; // @dynamic instantMessageAddresses;
@property(copy) NSArray *dates; // @dynamic dates;
@property(copy) NSArray *urlAddresses; // @dynamic urlAddresses;
@property(copy) NSArray *emailAddresses; // @dynamic emailAddresses;
@property(copy) NSArray *phoneNumbers; // @dynamic phoneNumbers;
- (void)setPreferredForPhoto;
- (void)setPreferredForName;
@property long long contactType; // @dynamic contactType;
@property(copy) NSString *note; // @dynamic note;
@property(copy) NSArray *birthdays; // @dynamic birthdays;
@property(copy) NSDateComponents *alternateBirthday; // @dynamic alternateBirthday;
@property(copy) NSDateComponents *birthday; // @dynamic birthday;
@property(copy) NSString *jobTitle; // @dynamic jobTitle;
@property(copy) NSString *departmentName; // @dynamic departmentName;
@property(copy) NSString *organizationName; // @dynamic organizationName;
@property(copy) NSString *phoneticFamilyName; // @dynamic phoneticFamilyName;
@property(copy) NSString *phoneticMiddleName; // @dynamic phoneticMiddleName;
@property(copy) NSString *phoneticGivenName; // @dynamic phoneticGivenName;
@property(copy) NSString *nickname; // @dynamic nickname;
@property(copy) NSString *previousFamilyName; // @dynamic previousFamilyName;
@property(copy) NSString *nameSuffix; // @dynamic nameSuffix;
@property(copy) NSString *familyName; // @dynamic familyName;
@property(copy) NSString *middleName; // @dynamic middleName;
@property(copy) NSString *givenName; // @dynamic givenName;
@property(copy) NSString *namePrefix; // @dynamic namePrefix;
- (void)_setValue:(id)arg1 forProperty:(int)arg2;
- (void)updateContactType:(_Bool)arg1;
- (_Bool)isEqualToContact:(id)arg1 includeIdentifiers:(_Bool)arg2;
- (_Bool)isEqualToContact:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)initWithRecord:(void *)arg1 unify:(_Bool)arg2 originalRecord:(void *)arg3;
- (id)initWithRecord:(void *)arg1;
- (id)init;

@end

