//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (CKUtilsAdditions)
- (id)CKUnmangledDocumentNameFromURLFragment;
- (id)CKMangledDocumentNameForURLFragment;
- (id)CKSafeStringForURLWithCharsToBeEscaped:(id)arg1 charsToLeaveUnescaped:(id)arg2;
- (id)CKSafeStringForURLPathComponent;
- (id)CKSafeHashStringForPathComponent;
- (id)CKSafeStringForPathComponent;
@end

