//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PUBadgeManager : NSObject
{
}

+ (id)defaultManager;
- (_Bool)isSmallBadge:(long long)arg1;
- (id)_imageNameForBadgeType:(long long)arg1;
- (struct UIOffset)imageOffsetForBadgeType:(long long)arg1;
- (id)imageForBadgeType:(long long)arg1;
- (long long)_badgeTypeForPLAsset:(id)arg1 size:(long long)arg2;
- (long long)_badgeTypeForPHAsset:(id)arg1 size:(long long)arg2;
- (long long)badgeTypeForAsset:(id)arg1 size:(long long)arg2;
- (long long)badgeTypeForAsset:(id)arg1;
- (long long)badgeTypeForCollection:(id)arg1 size:(long long)arg2;
- (long long)badgeTypeForCollection:(id)arg1;

@end

