//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotosUI/PUSettings.h>

@class PUFeedSettings, PUMomentsSettings, PUPhotoEditProtoSettings, PUPhotosGridSettings, PUSizeSettings;

@interface PURootSettings : PUSettings
{
    PUPhotosGridSettings *_photosGridSettings;
    PUPhotoEditProtoSettings *_photoEditingSettings;
    PUFeedSettings *_feedSettings;
    PUMomentsSettings *_momentsSettings;
    PUSizeSettings *_sizeSettings;
    unsigned long long _settingsVersion;
    long long _imagePickerTestSourceType;
}

+ (void)_deleteAllDiagnosticFiles;
+ (void)_setDebugRows:(id)arg1;
+ (id)_debugRowsForViewControllerStack:(id)arg1;
+ (void)_addRandomPhoto;
+ (id)_currentViewControllerStack;
+ (void)presentSettingsController;
+ (id)settingsControllerModule;
+ (id)sharedInstance;
@property(nonatomic) long long imagePickerTestSourceType; // @synthesize imagePickerTestSourceType=_imagePickerTestSourceType;
@property(nonatomic) unsigned long long settingsVersion; // @synthesize settingsVersion=_settingsVersion;
@property(retain, nonatomic) PUSizeSettings *sizeSettings; // @synthesize sizeSettings=_sizeSettings;
@property(retain, nonatomic) PUMomentsSettings *momentsSettings; // @synthesize momentsSettings=_momentsSettings;
@property(retain, nonatomic) PUFeedSettings *feedSettings; // @synthesize feedSettings=_feedSettings;
@property(retain, nonatomic) PUPhotoEditProtoSettings *photoEditingSettings; // @synthesize photoEditingSettings=_photoEditingSettings;
@property(retain, nonatomic) PUPhotosGridSettings *photosGridSettings; // @synthesize photosGridSettings=_photosGridSettings;
- (void).cxx_destruct;
- (void)setDefaultValues;
- (void)_save;

@end

