//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LAContextCallbackXPC.h"
#import "LAContextXPC.h"

@class NSData, NSError, NSMutableArray, NSString, NSXPCConnection;

@interface LAClient : NSObject <LAContextXPC, LAContextCallbackXPC>
{
    id <LAContextXPC> _remoteContext;
    NSXPCConnection *_daemonConnection;
    NSError *_permanentError;
    NSString *_creatorName;
    NSMutableArray *_callInvalidationBlocks;
    _Bool _shouldRecoverConnection;
    NSData *_externalizedContext;
    id <LAUIDelegate> _uiDelegate;
    NSData *_connectToContext;
}

+ (void)clientWithExternalizedContext:(id)arg1 uiDelegate:(id)arg2 reply:(CDUnknownBlockType)arg3;
+ (id)clientWithExternalizedContext:(id)arg1 uiDelegate:(id)arg2 error:(id *)arg3;
@property(retain, nonatomic) NSData *connectToContext; // @synthesize connectToContext=_connectToContext;
@property(nonatomic) __weak id <LAUIDelegate> uiDelegate; // @synthesize uiDelegate=_uiDelegate;
@property(readonly) NSData *externalizedContext; // @synthesize externalizedContext=_externalizedContext;
- (void).cxx_destruct;
@property(readonly) NSString *creatorDisplayName;
- (void)creatorName:(CDUnknownBlockType)arg1;
- (void)enterPassword:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)failProcessedEvent:(long long)arg1 failureError:(id)arg2 reply:(CDUnknownBlockType)arg3;
- (void)evaluateACL:(id)arg1 operation:(id)arg2 options:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (void)evaluatePolicy:(long long)arg1 options:(id)arg2 reply:(CDUnknownBlockType)arg3;
- (_Bool)_setPermanentError:(id)arg1;
- (void)invalidate;
- (void)dealloc;
- (void)invalidatedWithError:(id)arg1;
- (void)_recoverConnection;
- (void)_scheduleRecovery;
- (void)setupDaemonConnection:(id)arg1 remoteContext:(id)arg2 constInfo:(id)arg3;

@end

