//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLIntersiloServiceProtocol.h"

@interface _CLMainService : NSObject <CLIntersiloServiceProtocol>
{
    _Bool _valid;
}

+ (_Bool)isSupported;
+ (void)becameFatallyBlocked:(id)arg1;
+ (id)getSilo;
@property(nonatomic) _Bool valid; // @synthesize valid=_valid;

@end

