//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreMotion/CLNotifierServiceAdapter.h>

#import "CLGyroCalibrationDatabaseRemoteProtocol.h"

@interface CLGyroCalibrationDatabaseRemoteAdapter : CLNotifierServiceAdapter <CLGyroCalibrationDatabaseRemoteProtocol>
{
}

+ (void)becameFatallyBlocked:(id)arg1;
+ (id)getSilo;
+ (_Bool)isSupported;
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;
- (void)doAsync:(CDUnknownBlockType)arg1;
- (struct CLGyroCalibrationDatabaseRemote *)adaptee;
- (void)endService;
- (void)beginService;
- (id)initInSilo:(id)arg1;

// Remaining properties
@property(nonatomic) _Bool valid;

@end

