//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMNatalimeterInternal;

@interface CMNatalimeter : NSObject
{
    CMNatalimeterInternal *_internal;
}

+ (id)maxNatalieEntries;
+ (_Bool)isNatalimeterAvailable;
+ (_Bool)setUserProfile:(id)arg1 error:(id *)arg2;
+ (id)defaultUserProfile;
+ (id)userProfile;
@property(readonly, nonatomic) CMNatalimeterInternal *_internal; // @synthesize _internal;
- (unsigned long long)getSupportedMetricsForSession:(long long)arg1;
- (void)stopAbsoluteNatalimetryDataUpdates;
- (void)startAbsoluteNatalimetryDataUpdatesWithHandler:(CDUnknownBlockType)arg1;
- (void)queryAbsoluteNatalimetryDataSinceDataRecord:(id)arg1 withHandler:(CDUnknownBlockType)arg2;
- (void)queryAbsoluteNatalimetryDataSinceRecord:(long long)arg1 withHandler:(CDUnknownBlockType)arg2;
- (void)setSession:(long long)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)init;

@end

