//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SLSheetPreviewView.h"

@class NSArray, NSMutableDictionary, UIActivityIndicatorView, UIImage, UIImageView;

@interface SLSheetImagePreviewView : UIView <SLSheetPreviewView>
{
    UIImage *_image;
    _Bool _isTranscoding;
    _Bool _sheetPresentationAnimationDidFinish;
    UIActivityIndicatorView *_activityView;
    NSMutableDictionary *_intrinsicSizes;
    _Bool _needsLayout;
    UIImageView *_imageView;
    NSArray *_principalAttachments;
    long long _currentBarMetrics;
}

+ (id)blankWebpageImage;
@property(nonatomic) long long currentBarMetrics; // @synthesize currentBarMetrics=_currentBarMetrics;
@property(retain, nonatomic) NSArray *principalAttachments; // @synthesize principalAttachments=_principalAttachments;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)sheetPresentationAnimationDidFinish;
@property(nonatomic) _Bool isTranscoding;
- (void)_setUpActivityViewIfNecessary;
- (struct CGSize)intrinsicContentSize;
- (_Bool)previewDependsOnAttachment:(id)arg1;
- (void)setPreviewImage:(id)arg1 forAttachment:(id)arg2;
@property(retain, nonatomic) UIImage *image;
- (void)barMetricsDidChange;
- (struct CGSize)sizeForBarMetrics:(long long)arg1;
- (void)setSize:(struct CGSize)arg1 forBarMetrics:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

