//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "ABPeoplePickerHostViewControllerDelegate.h"

@class ABPeoplePickerHostViewControllerProxy, NSArray;

@interface _ABPeoplePickerNavigationController : UINavigationController <ABPeoplePickerHostViewControllerDelegate>
{
    ABPeoplePickerHostViewControllerProxy *_hostViewControllerProxy;
    void *_addressBook;
    NSArray *_displayedProperties;
    id <_ABPeoplePickerNavigationControllerDelegate> _peoplePickerDelegate;
}

@property(nonatomic) id <_ABPeoplePickerNavigationControllerDelegate> peoplePickerDelegate; // @synthesize peoplePickerDelegate=_peoplePickerDelegate;
- (_Bool)shouldContinueAfterSelectingPerson:(int)arg1 vcard:(id)arg2 property:(int)arg3 identifier:(int)arg4;
- (_Bool)shouldContinueAfterSelectingPerson:(int)arg1 vcard:(id)arg2;
- (void)didCancel;
@property(nonatomic) void *addressBook;
@property(copy, nonatomic) NSArray *displayedProperties;
- (void)setNavigationBarHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutomaticallyForwardRotationMethods;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;
- (id)initWithStyle:(int)arg1;
- (id)initWithAddressBook:(void *)arg1;
- (id)initAsAddressBook:(_Bool)arg1;
- (id)initAsAddressBook:(_Bool)arg1 withStyle:(int)arg2;
- (id)initAsAddressBook:(_Bool)arg1 withAddressBook:(void *)arg2;
- (id)initAsAddressBook:(_Bool)arg1 withAddressBook:(void *)arg2 withStyle:(int)arg3;

@end

