//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ABPropertyGroupItemDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ABCachingTableView, ABContactPhotoView, CNContact, NSArray, NSDictionary, NSString, UIColor, UILabel;

@interface ABContactHeaderView : UIView <UITableViewDelegate, UITableViewDataSource, ABPropertyGroupItemDelegate>
{
    ABContactPhotoView *_photoView;
    UILabel *_nameLabel;
    UILabel *_taglineLabel;
    ABCachingTableView *_editingTable;
    CNContact *_contact;
    UIView *_personHeaderView;
    _Bool _needsReload;
    _Bool _editing;
    id <ABPresenterDelegate> _delegate;
    UIColor *_backgroundColor;
    NSDictionary *_nameTextAttributes;
    NSDictionary *_taglineTextAttributes;
    NSArray *_editingGroups;
    NSString *_alternateName;
    NSString *_message;
    NSArray *_headerConstraints;
    UIView *_sizedToFitForSuperview;
    struct UIEdgeInsets _contentMargins;
}

+ (_Bool)requiresConstraintBasedLayout;
+ (id)contactHeaderViewWithContact:(id)arg1 editingGroups:(id)arg2 personHeaderView:(id)arg3;
+ (void)preCacheEdit;
+ (void)preCacheDisplay;
+ (void)preCacheContent;
@property(nonatomic) UIView *sizedToFitForSuperview; // @synthesize sizedToFitForSuperview=_sizedToFitForSuperview;
@property(retain, nonatomic) NSArray *headerConstraints; // @synthesize headerConstraints=_headerConstraints;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *alternateName; // @synthesize alternateName=_alternateName;
@property(retain, nonatomic) NSArray *editingGroups; // @synthesize editingGroups=_editingGroups;
@property(nonatomic, getter=isEditing) _Bool editing; // @synthesize editing=_editing;
@property(nonatomic) struct UIEdgeInsets contentMargins; // @synthesize contentMargins=_contentMargins;
@property(copy, nonatomic) NSDictionary *taglineTextAttributes; // @synthesize taglineTextAttributes=_taglineTextAttributes;
@property(copy, nonatomic) NSDictionary *nameTextAttributes; // @synthesize nameTextAttributes=_nameTextAttributes;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) id <ABPresenterDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *personHeaderView; // @synthesize personHeaderView=_personHeaderView;
- (void)menuWillHide:(id)arg1;
- (void)handleNameLabelLongPress:(id)arg1;
- (id)_taglineStringForContact:(id)arg1;
- (id)_headerStringForContact:(id)arg1;
- (void)_updatePhotoView;
- (double)_topMarginToNameBaselineWithName:(id)arg1 tagline:(id)arg2;
- (id)_phoneticNameForValue:(id)arg1 isFamilyName:(_Bool)arg2;
- (void)propertyItem:(id)arg1 willChangeValue:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)copy:(id)arg1;
- (id)selectEditingGroupAtIndex:(unsigned long long)arg1;
- (void)saveContactPhoto;
- (void)reloadData;
- (void)reloadDataIfNeeded;
- (void)setNeedsReload;
- (void)updateWithNewContact:(id)arg1;
- (id)contentViewEditingConstraints;
- (id)contentViewConstraints;
- (void)updateConstraints;
- (void)setEditingGroups:(id)arg1 withUpdate:(_Bool)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (double)_labelsVSpacing;
- (void)willMoveToSuperview:(id)arg1;
- (void)updateFontSizes;
- (void)tintColorDidChange;
- (void)dealloc;
- (id)initWithContact:(id)arg1 withEditingGroups:(id)arg2 personHeaderView:(id)arg3 frame:(struct CGRect)arg4;

@end

