//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class ABCardGroupItem, UIColor, UIView;

@interface ABContactCell : UITableViewCell
{
    _Bool _showSeparator;
    _Bool _hasBeenDisplayed;
    UIView *_separatorView;
    ABCardGroupItem *_cardGroupItem;
    double _leftContentMargin;
    double _rightContentMargin;
    UIColor *_contactSeparatorColor;
}

@property(nonatomic) _Bool hasBeenDisplayed; // @synthesize hasBeenDisplayed=_hasBeenDisplayed;
@property(retain, nonatomic) UIColor *contactSeparatorColor; // @synthesize contactSeparatorColor=_contactSeparatorColor;
@property(nonatomic) double rightContentMargin; // @synthesize rightContentMargin=_rightContentMargin;
@property(nonatomic) double leftContentMargin; // @synthesize leftContentMargin=_leftContentMargin;
@property(retain, nonatomic) ABCardGroupItem *cardGroupItem; // @synthesize cardGroupItem=_cardGroupItem;
@property(nonatomic) _Bool showSeparator; // @synthesize showSeparator=_showSeparator;
@property(readonly, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
- (void)layoutSubviews;
- (void)setNeedsLayout;
- (void)performAccessoryAction;
- (_Bool)shouldPerformAccessoryAction;
- (void)performDefaultAction;
- (_Bool)shouldPerformDefaultAction;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

