//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AddressBookUI/ABPropertyGroupItem.h>

@interface ABPropertyGroupAlertItem : ABPropertyGroupItem
{
}

- (id)_vibrationManager;
- (id)_toneManger;
- (id)description;
- (_Bool)isEquivalentToItem:(id)arg1 whenEditing:(_Bool)arg2;
@property(readonly, nonatomic, getter=isVibration) _Bool vibration;
@property(readonly, nonatomic, getter=isTone) _Bool tone;
- (_Bool)canRemove;
- (id)displayStringForValue:(id)arg1;
- (id)displayLabel;

@end

