//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AddressBookUI/ABPropertySimpleCell.h>

@interface ABPropertyEmailAddressCell : ABPropertySimpleCell
{
    _Bool _VIP;
}

@property(nonatomic, getter=isVIP) _Bool VIP; // @synthesize VIP=_VIP;
- (void)updateTransportButtons;
- (_Bool)shouldPerformDefaultAction;
- (void)updateWithPropertyItem:(id)arg1;
- (void)_updateStar;

@end

