//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AddressBookUI/ABPropertySimpleCell.h>

@class NSString;

@interface ABPropertyPhoneNumberCell : ABPropertySimpleCell
{
    NSString *_previousValue;
}

- (CDStruct_856ef1b3)suggestionsForString:(id)arg1 inputIndex:(unsigned int)arg2;
- (void)updateTransportButtons;
- (_Bool)shouldPerformDefaultAction;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)dealloc;

@end

