//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFAttachment.h"

@class NSString;

@interface MFAttachment (Utilities)
- (_Bool)hasCalendarMetadata;
@property(retain, nonatomic) NSString *icsRepresentation;
@property(retain, nonatomic) NSString *meetingStorePersistentID;
@property(retain, nonatomic) NSString *eventID;
- (void)writeToDiskWithData:(id)arg1;
- (id)filenameStrippingZipIfNeededUseApplications:(_Bool)arg1;
- (_Bool)isDisplayableInlineWithData:(id)arg1;
- (_Bool)isDisplayableInsidePluginWithData:(id)arg1;
- (_Bool)isDisplayableInline;
- (_Bool)isDisplayableInsidePlugin;
- (_Bool)isDisplayableByWebKit;
- (_Bool)isDisplayableImage;
- (_Bool)isContentOpenable;
- (_Bool)isContentTypeDisplayableByMobileMail;
- (_Bool)isCalendarFile;
- (_Bool)isRFC822;
- (_Bool)isPDFFile;
- (_Bool)isMedia;
- (_Bool)isImageFile;
- (_Bool)isRestrictedMIMEType;
- (id)fileAttributes;
- (id)contentType;
- (id)_contentTypeByStrippingZipIfNeeded:(_Bool)arg1;
@end

