//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PassKit/PKPaymentCardDetailsViewController.h>

#import "PKPaymentCameraCaptureViewControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class NSArray, NSDateFormatter, NSString, UIButton, UIDatePicker, UITableViewCell, UITextField;

@interface PKPaymentCardManualEntryViewController : PKPaymentCardDetailsViewController <UITextFieldDelegate, PKPaymentCameraCaptureViewControllerDelegate>
{
    UITextField *_nameField;
    UITextField *_cardNumberField;
    UITextField *_expirationDateField;
    UIButton *_photoButton;
    UITableViewCell *_cardHolderNameCell;
    UITableViewCell *_cardNumberCell;
    UITableViewCell *_expirationDateCell;
    UITableViewCell *_securityCodeCell;
    UIDatePicker *_expirationDatePicker;
    NSDateFormatter *_dateFormatter;
    void *_unifiedMeCard;
    _Bool _hasScrolledToShowFields;
    _Bool _hasShown;
    _Bool _cardNumberHasBecomeFirstResponder;
    _Bool _isCUPDebit;
    NSArray *_sortedCUPDebitBins;
}

- (void)_setCUPDebitFieldsDisabled:(_Bool)arg1;
- (_Bool)_isCUPDebit:(id)arg1;
- (id)defaultHeaderViewSubTitle;
- (id)defaultHeaderViewTitle;
- (void)handleNext:(id)arg1;
- (void)_clearTextFieldColors;
- (void)_checkAndAdjustForCUPDebit:(id)arg1;
- (void)cameraCaptureViewController:(id)arg1 didRecognizeObjects:(id)arg2;
- (void)cameraCaptureViewControllerDidFail:(id)arg1;
- (void)_dismissCameraCaptureViewController:(id)arg1;
- (void)_cameraCaptureCancelButtonPressed:(id)arg1;
- (void)_captureFromCamera:(id)arg1;
- (id)_name;
- (void)_displayNewExpiration:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)_updateTextField:(id)arg1 withDate:(id)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (id)_securityCodeCell;
- (id)_expirationDateCell;
- (id)_cardNumberCell;
- (id)_cardHolderNameCell;
- (id)_defaultCell;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)firstEmptyField;
- (id)dummyTextField;
- (_Bool)isEmpty;
- (_Bool)isComplete;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithWebService:(id)arg1 context:(long long)arg2 setupDelegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

