//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class PKPaymentSetupHeroView, PKPaymentSetupInfoView, UIImageView;

@interface PKPaymentSetupIntroView : UIView
{
    PKPaymentSetupHeroView *_heroView;
    long long _context;
    UIImageView *_heroImage;
    PKPaymentSetupInfoView *_infoView;
}

@property(retain, nonatomic) PKPaymentSetupInfoView *infoView; // @synthesize infoView=_infoView;
@property(retain, nonatomic) UIImageView *heroImage; // @synthesize heroImage=_heroImage;
- (_Bool)isBuddyiPad;
- (void)stopAnimation;
- (void)startAnimation;
- (void)layoutSubviews;
- (void)_createSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 context:(long long)arg2;

@end

