//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PKPassbookSettingsDataSource.h"

@class NSString, PKPassLibraryDefaultDataProvider, PKPaymentOptionsDefaults, PKPaymentService;

@interface PKPassbookSettingsDefaultBehavior : NSObject <PKPassbookSettingsDataSource>
{
    PKPaymentService *_paymentService;
    PKPassLibraryDefaultDataProvider *_passDataProvider;
    PKPaymentOptionsDefaults *_options;
}

- (id)secureElementID;
- (_Bool)showPassState;
- (id)optionsDelegate;
- (id)passDataProvider;
- (id)setupDelegate;
- (_Bool)deviceSupportsInAppPayments;
- (_Bool)deviceInRestrictedMode;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

