//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, UIImageView;

@interface PKPaymentSetupHeroView : UIView
{
    long long _context;
    unsigned long long _screenType;
    _Bool _isAnimating;
    UIImageView *_heroImageView;
    UIImageView *_presentedCard;
    NSMutableArray *_cardViews;
}

- (unsigned long long)_indexOfNextObject:(id)arg1 withArray:(id)arg2;
- (void)_transitionFromCard:(id)arg1 toCard:(id)arg2;
- (void)stopAnimation;
- (void)startAnimation;
- (void)layoutSubviews;
- (void)_createCardViews:(id)arg1;
- (void)_createSubviews;
- (void)dealloc;
- (id)initWithContext:(long long)arg1 screenType:(unsigned long long)arg2;

@end

