//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class PKPaymentApplication, PKPaymentPass, UIActivityIndicatorView, UIColor, UIImageView, UILabel;

@interface PKPaymentPassTableCell : UITableViewCell
{
    PKPaymentPass *_pass;
    PKPaymentApplication *_paymentApplication;
    UILabel *_mainLabel;
    UILabel *_secondaryLabel;
    UILabel *_passStateLabel;
    UIImageView *_snapshotView;
    UIActivityIndicatorView *_activityIndicator;
    _Bool _showState;
    UIColor *_mainLabelColor;
    UIColor *_subTextLabelColor;
    UIColor *_highlightColor;
}

@property(nonatomic) UIColor *highlightColor; // @synthesize highlightColor=_highlightColor;
@property(nonatomic) UIColor *subTextLabelColor; // @synthesize subTextLabelColor=_subTextLabelColor;
@property(nonatomic) UIColor *mainLabelColor; // @synthesize mainLabelColor=_mainLabelColor;
- (id)_textColorForPassState:(unsigned long long)arg1;
- (id)_stringForPassState:(unsigned long long)arg1;
- (void)setShowPassState:(_Bool)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithPass:(id)arg1 secureElementIdentifier:(id)arg2;

@end

