//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PKPaymentServiceDelegate.h"

@class NSArray, NSString, PKPaymentSetupAboutViewController, PSSpecifier;

@interface PKPassbookSettingsController : NSObject <PKPaymentServiceDelegate>
{
    id <PKPassbookSettingsDelegate> _delegate;
    id <PKPassbookSettingsDataSource> _dataSource;
    id <PKPassLibraryDataProvider> _passLibraryDataProvider;
    id <PKPassbookSettingsOptionsDelegate> _optionsDelegate;
    PKPaymentSetupAboutViewController *_privacyController;
    long long _context;
    NSString *_defaultCardIdentifier;
    NSArray *_passes;
    PSSpecifier *_addCardButtonSpecifier;
    PSSpecifier *_cardsGroupSpecifier;
    PSSpecifier *_defaultPaymentSpecifier;
    PSSpecifier *_defaultShippingAddressSpecifier;
    PSSpecifier *_defaultContactEmailSpecifier;
    PSSpecifier *_defaultContactPhoneSpecifier;
}

@property(nonatomic) id <PKPassbookSettingsDelegate> delegate; // @synthesize delegate=_delegate;
- (id)_displayableStringForLabeledValue:(id)arg1;
- (id)_getDefaultContactPhone;
- (id)_getDefaultContactEmail;
- (id)_getDefaultShippingAddress;
- (void)_showDefaultContactPhoneOptions:(id)arg1;
- (void)_showDefaultContactEmailOptions:(id)arg1;
- (void)_showDefaultShippingAddressOptions:(id)arg1;
- (id)_defaultContactPhoneSpecifier;
- (id)_defaultContactEmailSpecifier;
- (id)_defaultShippingAddressSpecifier;
- (id)_getDefaultPaymentCard;
- (id)_defaultPaymentSpecifier;
- (void)done:(id)arg1;
- (void)_openPrivacyLink;
- (void)_showDefaultPaymentOptions:(id)arg1;
- (id)_defaultsGroupSpecifiers;
- (void)_showCardDetails:(id)arg1;
- (id)_cardListSpecifiers;
- (void)_addPaymentCard;
- (id)_addCardButtonSpecifier;
- (void)addCardTapped;
- (void)removeFooterForSpecifier:(id)arg1;
- (void)refreshDefaultCard;
- (void)refreshPasses;
- (id)specifiers;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 dataSource:(id)arg2 context:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

