//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PKPaymentSetupPrivacyFooterViewDelegate.h"

@class ACAccountStore, NSArray, PKPaymentWebService;

@interface PKPaymentSetupViewController : UIViewController <PKPaymentSetupPrivacyFooterViewDelegate>
{
    ACAccountStore *_accountStore;
    PKPaymentWebService *_webService;
    id <PKPaymentSetupViewControllerDelegate> _delegate;
    NSArray *_eligibleCards;
    long long _context;
}

@property(nonatomic) long long context; // @synthesize context=_context;
@property(retain, nonatomic) PKPaymentWebService *webService; // @synthesize webService=_webService;
@property(retain, nonatomic) NSArray *eligibleCards; // @synthesize eligibleCards=_eligibleCards;
@property(nonatomic) id <PKPaymentSetupViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)_contextSpecificStringForAggdKey:(id)arg1;
- (id)_deviceSpecificLocalizedStringKeyForKey:(id)arg1;
- (void)_pushCardList:(id)arg1;
- (void)_pushCardDetailsViewControllerForCredential:(id)arg1;
- (void)_pushCardEntryViewController;
- (void)dismissAboutView:(id)arg1;
- (void)privacyFooterLinkTapped:(id)arg1;
- (void)_next:(id)arg1;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (unsigned long long)edgesForExtendedLayout;
- (void)loadView;
- (id)initWithPaymentWebService:(id)arg1 eligibleCards:(id)arg2 context:(long long)arg3 delegate:(id)arg4;

@end

