//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class PKPaymentSetupPrivacyFooterView, UIActivityIndicatorView, UIImageView, UILabel;

@interface PKPaymentSetupInfoView : UIView
{
    UIImageView *_logo;
    UILabel *_bodyLabel;
    PKPaymentSetupPrivacyFooterView *_privacyFooter;
    long long _context;
    UIActivityIndicatorView *_activityIndicatorView;
}

@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(nonatomic) long long context; // @synthesize context=_context;
@property(retain, nonatomic) PKPaymentSetupPrivacyFooterView *privacyFooter; // @synthesize privacyFooter=_privacyFooter;
- (_Bool)isBuddyiPad;
- (id)_bodyFont;
- (id)_titleFont;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)bodyLabel;
- (id)logo;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 context:(long long)arg2;

@end

