//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSArray, PKCameraCaptureInstructionView, PKPaymentCardManualEntryViewController, UIView;

@interface PKPaymentCameraCaptureViewController : UIViewController
{
    NSArray *_outputObjects;
    PKCameraCaptureInstructionView *_cameraInstructionView;
    PKPaymentCardManualEntryViewController *_manualEntryController;
    id <PKPaymentCameraCaptureViewControllerDelegate> _cameraCaptureDelegate;
    long long _context;
    id <PKPaymentSetupViewControllerDelegate> _setupDelegate;
    UIView *_cameraView;
    _Bool _hideSetupLaterButton;
}

@property(nonatomic) _Bool hideSetupLaterButton; // @synthesize hideSetupLaterButton=_hideSetupLaterButton;
- (void)_pushManualEntryViewControllerAndRemoveSelf;
- (void)_setupLater:(id)arg1;
- (void)_manualEntryButtonPressed:(id)arg1;
- (_Bool)isBuddyiPad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithCameraCaptureDelegate:(id)arg1;
- (id)initWithWebService:(id)arg1 context:(long long)arg2 setupDelegate:(id)arg3;
- (id)init;

@end

