//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PassKit/PKPaymentSetupTableViewController.h>

#import "UITextFieldDelegate.h"

@class CLInUseAssertion, NSString, PKPaymentCredential, PKPaymentWebService, PKWeakReference, RemoteUIController, UITextField;

@interface PKPaymentCardDetailsViewController : PKPaymentSetupTableViewController <UITextFieldDelegate>
{
    RemoteUIController *_termsUIController;
    CLInUseAssertion *_CLInUse;
    double _maxHeaderWidth;
    _Bool _maxHeaderWidthCalculated;
    _Bool _isCUPDebit;
    UITextField *_dummyTextField;
    PKWeakReference *_setupDelegate;
    _Bool _termsPresented;
    _Bool _hideSetupLaterButton;
    _Bool _verifying;
    PKPaymentWebService *_webService;
    PKPaymentCredential *_paymentCredential;
    UITextField *_cscField;
}

+ (void)handlePassAlreadyProvisionedError;
+ (void)handleProvisioningError:(id)arg1 forApplicationIdentifier:(id)arg2 withSetupDelegate:(id)arg3;
+ (void)handleDownloadedPasses:(id)arg1 fromViewController:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic, getter=isVerifying) _Bool verifying; // @synthesize verifying=_verifying;
@property(retain, nonatomic) UITextField *cscField; // @synthesize cscField=_cscField;
@property(retain, nonatomic) PKPaymentCredential *paymentCredential; // @synthesize paymentCredential=_paymentCredential;
@property(nonatomic) _Bool hideSetupLaterButton; // @synthesize hideSetupLaterButton=_hideSetupLaterButton;
@property(retain, nonatomic) PKPaymentWebService *webService; // @synthesize webService=_webService;
@property(nonatomic) id <PKPaymentSetupViewControllerDelegate> setupDelegate;
- (id)_imageForCredential:(id)arg1;
- (id)_contextSpecificStringForAggdKey:(id)arg1;
- (void)_setNavigationBarEnabled:(_Bool)arg1;
- (void)_stopVerifyingUI;
- (void)_showVerifiedUI;
- (void)_showVerifyingUI;
- (void)_showEligibilityIssueWithCredential:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_showProvisioningError:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)_showSetupAssistantVerificationAlertForRecord:(id)arg1 pass:(id)arg2;
- (void)_showVerificationMethodsForPass:(id)arg1;
- (id)defaultHeaderViewSubTitle;
- (id)defaultHeaderViewTitle;
- (void)setupLater:(id)arg1;
- (void)addDifferentCard:(id)arg1;
- (void)_handlePassSuccessfullyAdded:(id)arg1;
- (void)handleNext:(id)arg1;
- (void)textFieldDidChange:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)displayTermsForCredential:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)provisionCard:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)checkCard:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)dummyTextField;
@property(readonly, nonatomic, getter=isComplete) _Bool complete;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)headerView;
- (void)dealloc;
- (id)initWithWebService:(id)arg1 context:(long long)arg2 setupDelegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

