//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UIButton, UIImageView, UILabel;

@interface PKTableHeaderView : UIView
{
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIButton *_actionButton;
    UIActivityIndicatorView *_activityIndicator;
    UIImageView *_checkmarkView;
    _Bool _buddyPad;
    double _topPadding;
    double _bottomPadding;
}

@property(readonly, retain, nonatomic) UIImageView *checkmarkView; // @synthesize checkmarkView=_checkmarkView;
@property(readonly, retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(nonatomic) double bottomPadding; // @synthesize bottomPadding=_bottomPadding;
@property(nonatomic) double topPadding; // @synthesize topPadding=_topPadding;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic, getter=isBuddyPad) _Bool buddyPad; // @synthesize buddyPad=_buddyPad;
- (id)_subtitleFont;
- (id)_titleFont;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, retain, nonatomic) UIButton *actionButton;
@property(readonly, retain, nonatomic) UILabel *subtitleLabel;
@property(readonly, retain, nonatomic) UILabel *titleLabel;
- (void)dealloc;

@end

