//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UIButton;

@interface PKWelcomeHeaderView : UIView
{
    UIView *_titleView;
    UIButton *_actionButton;
    UIActivityIndicatorView *_activityIndicator;
    _Bool _showActivityIndicator;
    unsigned long long _passType;
}

@property(nonatomic) _Bool showActivityIndicator; // @synthesize showActivityIndicator=_showActivityIndicator;
@property(readonly, nonatomic) unsigned long long passType; // @synthesize passType=_passType;
- (void)_addTapped;
- (void)addTapped;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithPassType:(unsigned long long)arg1;
- (id)init;

@end

