//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EKCalendarItemEditItem, NSArray, NSDate, NSIndexPath, NSString, UIView, UIViewController;

@protocol EKCalendarItemEditItemDelegate <NSObject>
- (NSString *)defaultAlertTitleForEditItem:(EKCalendarItemEditItem *)arg1;

@optional
- (UIViewController *)viewControllerForEditItem:(EKCalendarItemEditItem *)arg1;
- (void)editItem:(EKCalendarItemEditItem *)arg1 textViewShouldReturn:(UIView *)arg2;
- (void)editItemRequiresPopoverSizeUpdate:(EKCalendarItemEditItem *)arg1;
- (void)editItemRequiresHeightChange:(EKCalendarItemEditItem *)arg1;
- (void)editItem:(EKCalendarItemEditItem *)arg1 didEndDatePickingAnimated:(_Bool)arg2;
- (void)editItem:(EKCalendarItemEditItem *)arg1 willBeginDatePickingWithDate:(NSDate *)arg2 action:(SEL)arg3 animated:(_Bool)arg4 forSubitem:(unsigned long long)arg5 inSubsection:(unsigned long long)arg6;
- (void)editItem:(EKCalendarItemEditItem *)arg1 wantsIndexPathsScrolledToVisible:(NSArray *)arg2;
- (void)editItem:(EKCalendarItemEditItem *)arg1 wantsRowReload:(NSIndexPath *)arg2;
- (void)editItem:(EKCalendarItemEditItem *)arg1 performActionsOnCellAtSubitem:(unsigned long long)arg2 inSubsection:(unsigned long long)arg3 actions:(void (^)(UITableViewCell *))arg4;
- (void)editItem:(EKCalendarItemEditItem *)arg1 wantsRowInsertions:(NSArray *)arg2 rowDeletions:(NSArray *)arg3 rowReloads:(NSArray *)arg4;
- (void)editItem:(EKCalendarItemEditItem *)arg1 wantsRowInsertions:(NSArray *)arg2 rowDeletions:(NSArray *)arg3;
- (void)editItem:(EKCalendarItemEditItem *)arg1 wantsDoneButtonDisabled:(_Bool)arg2;
- (void)editItem:(EKCalendarItemEditItem *)arg1 wantsKeyboardPinned:(_Bool)arg2;
- (void)editItemTextChanged:(EKCalendarItemEditItem *)arg1;
- (void)editItemDidEndEditing:(EKCalendarItemEditItem *)arg1;
- (void)editItem:(EKCalendarItemEditItem *)arg1 didCommitFromDetailViewController:(_Bool)arg2;
- (void)editItemDidStartEditing:(EKCalendarItemEditItem *)arg1;
@end

