//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class EKCalendarDate, EKUIOccurrenceTableViewCell, NSAttributedString, NSDictionary, NSString, UIColor;

@interface EKUIOccurrenceTableViewCellContentView : UIView
{
    EKUIOccurrenceTableViewCell *_hostCell;
    struct CGRect _primaryLabelFrame;
    struct CGRect _secondaryLabelFrame;
    struct CGRect _topTimeLabelFrame;
    struct CGRect _bottomTimeLabelFrame;
    struct CGRect _colorBarFrame;
    struct CGRect _angleStripeFrame;
    UIColor *_eventCalendarColor;
    EKCalendarDate *_eventStartDate;
    EKCalendarDate *_eventEndDate;
    NSAttributedString *_eventTitleAttrString;
    NSString *_eventTitle;
    NSString *_eventLocation;
    NSString *_topTimeString;
    NSString *_bottomTimeString;
    NSDictionary *_secondaryStringDrawingAttributes;
    NSDictionary *_topTimeStringDrawingAttributes;
    NSDictionary *_bottomTimeStringDrawingAttributes;
    long long _truncatingOptions;
    long long _nontruncatingOptions;
    _Bool _canUseFastestStringDrawingForPrimary;
    _Bool _canUseFastestStringDrawingForSecondary;
    _Bool _isAllDay;
    _Bool _isRecurring;
    _Bool _isBirthday;
    _Bool _isFacebook;
    _Bool _tentative;
    _Bool _declined;
    _Bool _needsReply;
    _Bool _cancelled;
}

- (void).cxx_destruct;
- (id)_textForBottomTimeLabel;
- (id)_textForTopTimeLabel;
- (_Bool)isDeclined;
- (_Bool)needsReply;
- (_Bool)isTentative;
- (_Bool)isFacebook;
- (_Bool)isBirthday;
- (_Bool)isCancelled;
- (_Bool)isAllDay;
- (id)_textLabelWithAddedImageAttachmentsFromText:(id)arg1 withFont:(id)arg2;
- (void)_addIcon:(id)arg1 toString:(id)arg2 withFont:(id)arg3;
- (void)_updateBottomTimeLabel;
- (void)_updateTopTimeLabel;
- (void)_updateSecondaryTextLabel;
- (void)_updatePrimaryTextLabel;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (void)updateWithEvent:(id)arg1 placedUnderDayWithStartDate:(id)arg2 showCalendarColors:(_Bool)arg3;
- (id)initWithHostCell:(id)arg1;

@end

