//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class EKUIOccurrenceTableViewCellContentView, UIView;

@interface EKUIOccurrenceTableViewCell : UITableViewCell
{
    EKUIOccurrenceTableViewCellContentView *_contentView;
    UIView *_separatorViewForNonOpaqueTables;
    _Bool _drawsOwnRowSeparators;
    _Bool _usesVibrantSeparatorOverlayDrawing;
    _Bool _usesInsetMargin;
}

+ (id)_tentativeAngledStripeBackground;
+ (id)_needsReplyAngledStripeBackground;
+ (id)_needsReplyDot;
+ (id)_facebookIcon;
+ (id)_birthdayIcon;
+ (double)_rightImageSpacing;
+ (double)tentativeStripeBackgroundAlpha;
+ (id)tentativeStripeColor;
+ (id)tentativeBackgroundColor;
+ (double)needsReplyStripeBackgroundAlpha;
+ (id)needsReplyStripeColor;
+ (id)needsReplyBackgroundColor;
+ (id)normalBackgroundColor;
+ (id)strikethroughTimeTextColor;
+ (id)normalBottomTimeTextColor;
+ (id)normalTopTimeTextColor;
+ (id)strikethroughSecondaryTextColor;
+ (id)normalSecondaryTextColor;
+ (id)strikethroughPrimaryTextColor;
+ (id)invitationPrimaryTextColor;
+ (id)prefixPrimaryTextColor;
+ (id)normalPrimaryTextColor;
+ (id)cancelledDeclinedColorBarColor;
+ (id)secondaryTextLabelFont;
+ (id)primaryTextLabelFont;
+ (id)timeLabelsFont;
+ (id)reuseIdentifier;
@property(nonatomic) _Bool usesInsetMargin; // @synthesize usesInsetMargin=_usesInsetMargin;
@property(nonatomic) _Bool usesVibrantSeparatorOverlayDrawing; // @synthesize usesVibrantSeparatorOverlayDrawing=_usesVibrantSeparatorOverlayDrawing;
@property(nonatomic) _Bool drawsOwnRowSeparators; // @synthesize drawsOwnRowSeparators=_drawsOwnRowSeparators;
- (void).cxx_destruct;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)updateWithEvent:(id)arg1 placedUnderDayWithStartDate:(id)arg2 showCalendarColors:(_Bool)arg3;
- (void)_setMarginExtendsToFullWidth:(_Bool)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

