//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MPAVPlaylistManager, MPQueueFeeder;

@protocol MPAVPlaylistManagerDelegate <NSObject>
- (void)playlistManager:(MPAVPlaylistManager *)arg1 didFailLoadingAllItemsForQueueFeeder:(MPQueueFeeder *)arg2;
- (void)playlistManager:(MPAVPlaylistManager *)arg1 didTransitionToPlaylistFeeder:(MPQueueFeeder *)arg2;
@end

