//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MPPlaybackContext : NSObject
{
    _Bool _shouldStartPlayback;
    _Bool _shouldRestartPlayback;
    long long _startIndex;
    unsigned long long _shuffleType;
    unsigned long long _repeatType;
}

+ (Class)queueFeederClass;
@property(nonatomic) unsigned long long repeatType; // @synthesize repeatType=_repeatType;
@property(nonatomic) unsigned long long shuffleType; // @synthesize shuffleType=_shuffleType;
@property(nonatomic) _Bool shouldRestartPlayback; // @synthesize shouldRestartPlayback=_shouldRestartPlayback;
@property(nonatomic) _Bool shouldStartPlayback; // @synthesize shouldStartPlayback=_shouldStartPlayback;
@property(nonatomic) long long startIndex; // @synthesize startIndex=_startIndex;
- (id)description;
- (id)descriptionComponents;
- (id)init;

@end

