//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MPQueueFeeder, NSError;

@protocol MPQueueFeederDelegate <NSObject>
- (void)queueFeeder:(MPQueueFeeder *)arg1 didChangeContentsWithPreferredStartIndex:(unsigned long long)arg2 error:(NSError *)arg3;
@end

