//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class MPMediaItem, MPMediaLibrary;

@interface MPMediaEntity : NSObject <NSCopying, NSSecureCoding>
{
}

+ (_Bool)supportsSecureCoding;
+ (_Bool)canFilterByProperty:(id)arg1;
@property(readonly, nonatomic) MPMediaLibrary *mediaLibrary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)enumerateValuesForProperties:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)valuesForProperties:(id)arg1;
- (id)valueForProperty:(id)arg1;
- (void)invalidateCachedProperties;
@property(readonly, nonatomic) MPMediaItem *representativeItem;
@property(readonly, nonatomic) unsigned long long persistentID;
@property(readonly, nonatomic) _Bool isPurchasableStoreOffer;
@property(readonly, nonatomic) _Bool isDownloadableStoreOffer;
@property(readonly, nonatomic) long long preferredStoreOfferVariant;
- (id)buyOffer;
- (id)completionOfferForVariant:(long long)arg1;
- (id)buyOfferForVariant:(long long)arg1;
@property(readonly, nonatomic) _Bool isDownloadable;

@end

