//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MPMediaLibraryDataProvider.h"

@class NSArray, NSDate, NSDictionary, NSIndexSet, NSString;

@protocol MPMediaLibraryDataProviderPrivate <MPMediaLibraryDataProvider>

@optional
@property(readonly, nonatomic) NSArray *localizedSectionIndexTitles;
@property(readonly, nonatomic) NSArray *preferredSubtitleLanguages;
@property(readonly, nonatomic) NSArray *preferredAudioLanguages;
@property(readonly, nonatomic) _Bool isGeniusEnabled;
@property(readonly, nonatomic) NSString *databasePath;
- (_Bool)setValue:(id)arg1 forDatabaseProperty:(NSString *)arg2;
- (id)valueForDatabaseProperty:(NSString *)arg1;
- (NSString *)localizedSectionHeaderForSectionIndex:(unsigned long long)arg1;
- (void)updateEntitesToCurrentRevision;
- (_Bool)supportsEntityChangeTrackingForMediaEntityType:(long long)arg1 collectionGroupingType:(long long)arg2 dataProviderClass:(out Class *)arg3;
- (void)populateLocationPropertiesOfItemWithIdentifier:(long long)arg1 withPath:(NSString *)arg2;
- (void)releaseGeniusClusterPlaylist:(void *)arg1;
- (long long *)generateItemIdentifiersForGeniusClusterPlaylist:(void *)arg1 count:(unsigned long long *)arg2 error:(id *)arg3;
- (void *)createGeniusClusterPlaylistWithSeedItemIdentifiers:(long long *)arg1 count:(unsigned long long)arg2 error:(id *)arg3;
- (void)seedPlaylistWithIdentifier:(long long)arg1 withItemWithIdentifier:(long long)arg2 completionBlock:(void (^)(_Bool, NSError *))arg3;
- (void)moveItemFromIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2 inPlaylistWithIdentifier:(long long)arg3 completionBlock:(void (^)(_Bool))arg4;
- (void)removeAllItemsInPlaylistWithIdentifier:(long long)arg1;
- (void)removeItemsWithIdentifiers:(long long *)arg1 atFilteredIndexes:(NSIndexSet *)arg2 inPlaylistWithIdentifier:(long long)arg3 completionBlock:(void (^)(_Bool))arg4;
- (void)addItemsWithIdentifiers:(long long *)arg1 count:(unsigned long long)arg2 toPlaylistWithIdentifier:(long long)arg3 completionBlock:(void (^)(_Bool))arg4;
- (void)addItemWithIdentifier:(long long)arg1 toPlaylistWithIdentifier:(long long)arg2 completionBlock:(void (^)(_Bool))arg3;
- (_Bool)removePlaylistWithIdentifier:(long long)arg1;
- (_Bool)removeItemsWithIdentifiers:(long long *)arg1 count:(unsigned long long)arg2 hideFromPurchaseHistory:(_Bool)arg3;
- (long long)addPlaylistWithValuesForProperties:(NSDictionary *)arg1;
- (void)setValue:(id)arg1 forProperty:(NSString *)arg2 ofCollectionWithIdentifier:(long long)arg3 groupingType:(long long)arg4 completionBlock:(void (^)(_Bool, NSError *))arg5;
- (void)setValue:(id)arg1 forProperty:(NSString *)arg2 ofPlaylistWithIdentifier:(long long)arg3 completionBlock:(void (^)(_Bool, NSError *))arg4;
- (void)setValue:(id)arg1 forProperty:(NSString *)arg2 ofItemWithIdentifier:(long long)arg3 completionBlock:(void (^)(_Bool, NSError *))arg4;
- (_Bool)isCurrentThreadInTransaction;
- (void)performReadTransactionWithBlock:(void (^)(void))arg1;
- (_Bool)performTransactionWithBlock:(_Bool (^)(void))arg1;
- (_Bool)isArtworkImageIdenticalForItemWithIdentifier:(long long)arg1 otherItemWithIdentifier:(long long)arg2 compareRepresentativeItemArtwork:(_Bool)arg3 missingAlwaysComparesEqual:(_Bool)arg4;
- (_Bool)hasArtworkImageForItemWithIdentifier:(long long)arg1;
- (NSString *)artworkCacheIDForItemWithIdentifier:(long long)arg1 atPlaybackTime:(double)arg2;
- (_Bool)shouldAsynchrounouslyLoadArtworkForItemWithIdentifier:(long long)arg1 artworkSize:(struct CGSize)arg2 artworkCacheID:(NSString *)arg3;
- (_Bool)shouldAsynchrounouslyLoadArtworkForItemWithIdentifier:(long long)arg1 artworkFormat:(long long)arg2 artworkCacheID:(NSString *)arg3;
- (void)loadBestArtworkImageForSize:(struct CGSize)arg1 forArtworkCacheID:(NSString *)arg2 completionBlock:(void (^)(UIImage *, struct CGRect, struct CGRect))arg3;
- (void)loadArtworkImageForFormat:(long long)arg1 ofItemWithArtworkCacheID:(NSString *)arg2 canUseSurfaceBackedImage:(_Bool)arg3 completionBlock:(void (^)(UIImage *, struct CGRect, struct CGRect))arg4;
- (void)loadArtworkImageForFormat:(long long)arg1 ofItemWithIdentifier:(long long)arg2 completionBlock:(void (^)(UIImage *, struct CGRect, struct CGRect))arg3;
- (long long)itemPersistentIDForStoreID:(long long)arg1;
- (_Bool)playlistExistsWithPersistentID:(unsigned long long)arg1;
- (_Bool)itemExistsWithPersistentID:(unsigned long long)arg1;
- (_Bool)hasUbiquitousBookmarkableItems;
- (_Bool)hasGeniusMixes;
- (_Bool)hasMediaOfType:(unsigned long long)arg1;
- (NSDate *)lastModifiedDate;
@end

