//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MediaPlayer/MPReportingTrackPlaybackEvent.h>

@class NSData;

@interface MPReportingTimedMetadataEvent : MPReportingTrackPlaybackEvent
{
    double _timestamp;
    NSData *_timedMetadata;
}

@property(copy, nonatomic) NSData *timedMetadata; // @synthesize timedMetadata=_timedMetadata;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
- (_Bool)isValid;

@end

