//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDictionary, NSObject<OS_dispatch_source>, UILabel;

@interface MPSkipLimitView : UIView
{
    NSObject<OS_dispatch_source> *_hideSourceTimer;
    UILabel *_informationLabel;
    _Bool _needsLabelUpdate;
    long long _numberOfAvailableSkips;
    long long _skipFrequency;
    double _skipInterval;
    NSDictionary *_textAttributes;
}

@property(copy, nonatomic) NSDictionary *textAttributes; // @synthesize textAttributes=_textAttributes;
@property(nonatomic) double skipInterval; // @synthesize skipInterval=_skipInterval;
@property(nonatomic) long long skipFrequency; // @synthesize skipFrequency=_skipFrequency;
@property(nonatomic) long long numberOfAvailableSkips; // @synthesize numberOfAvailableSkips=_numberOfAvailableSkips;
- (void).cxx_destruct;
- (void)_updateLabelIfNeeded;
- (void)_setNeedsLabelUpdate;
- (void)_hideSkipInformationAnimated:(_Bool)arg1;
- (void)showSkipInformationAnimated:(_Bool)arg1;
- (void)hideSkipInformationAfterDelay:(double)arg1 animated:(_Bool)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

