//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (FormatExtras)
+ (id)_maps_formatFloatForDistanceSign:(double)arg1;
+ (id)_maps_formattedStringForFloat:(double)arg1 useIncreasedPrecision:(_Bool)arg2;
+ (id)_maps_formattedStringForFloat:(double)arg1;
@end

