//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _HKBehavior : NSObject
{
}

+ (unsigned long long)currentDiskSpaceAvailable;
+ (unsigned long long)totalDiskCapacity;
+ (id)currentDiskUsage;
+ (id)currentOSBuild;
+ (id)currentDeviceProductType;
+ (id)currentDeviceDisplayName;
+ (_Bool)isNano;
+ (_Bool)isAppleInternalInstall;
+ (_Bool)isDeviceSupported;

@end

